Add ability to log to auditor
Firesphere/silverstripe-bootstrapmfa pull request #54
Opened 2018-11-30 02:27 UTC by Firesphere

- Add auditor to suggested modules
- Log all steps to logger

Issue: https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/33

2018-11-30 04:18 UTC, Firesphere commented
Failures of tests are fixed in a separate PR

2018-12-02 15:15 UTC, robbieaverill requested changes
I've linked this to https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/33 and left some minor comments on the proposed changes.

I'd note that the issue says "We should provide event hooks for https://github.com/silverstripe/silverstripe-auditor to pick up (and implement those listeners in the auditlog module)" - this is how the existing implementations of the auditor module work, and we should follow suit.

For example - where you've got `$this->log('Failure MFA login with ' . $authenticationMethod...` you'd instead use `$this->extend('onMFALoginFailure', $autheticationMethod)` or something, then implement the formatting logic into AuditHook, e.g. https://github.com/silverstripe/silverstripe-auditor/blob/846fdb30bf0c99f01d72ac21950eb997d3fc4ee0/code/AuditHook.php#L261-L280

2018-12-02 15:15 UTC, robbieaverill commented on src/Handlers/BootstrapMFALoginHandler.php
> +        if ($this->auditLogger) {
This property is undefined - you should define it and also add a public getter/setter for it

2018-12-02 15:15 UTC, robbieaverill commented on src/Handlers/BootstrapMFALoginHandler.php
> +        }
Minor: phpcs violation

2018-12-03 01:06 UTC, Firesphere commented
> We should provide event hooks for https://github.com/silverstripe/silverstripe-auditor to pick up (and implement those listeners in the auditlog module)

Sure. I, in this case, "just" followed the auditor docs. I'll update accordingly

2019-03-05 21:22 UTC, closed without merging